### ISSUE TITLE
kernel size in transformer

### ISSUE THREAD

**Issue by advaza** [joelmoniz/gogh-figure#1]
Hi Joel!
Thank you for your published code.
I've noticed that the kernel size of the second and third layers in the transformer model is 9 as opposed to the kernel size in the original paper, 3. Was it intentional?

Thank you,
Adva

**Comment by joelmoniz** [comment]
Great catch, thank you! I've updated the filters' kernel size to 3x3, and while training is now quicker, there seems to be no discernible difference in output quality on either the monet or miscellaneous datasets.
